name: build-macos

on:
  workflow_dispatch: {}
  workflow_call: {}

env:
  BUILD_TYPE: Release

jobs:
  build-darwin:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install rust toolchain
      run: |
        rustup target add x86_64-apple-darwin

    - name: Build macOS (x86_64-apple-darwin)
      if: '!cancelled()'
      run: |
        cargo build --target=x86_64-apple-darwin --release

    - name: Build macOS (aarch64-apple-darwin)
      if: '!cancelled()'
      run: |
        cargo build --target=aarch64-apple-darwin --release

    - name: Upload Artifact (x86_64-apple-darwin)
      uses: actions/upload-artifact@v4
      if: '!cancelled()'
      with:
        name: built-x64-osx
        path: ${{github.workspace}}/target/x86_64-apple-darwin/release/soplink

    - name: Upload Artifact (aarch64-apple-darwin)
      uses: actions/upload-artifact@v4
      if: '!cancelled()'
      with:
        name: built-arm64-osx
        path: ${{github.workspace}}/target/aarch64-apple-darwin/release/soplink
